[site]
title = "TheElectronWill's blog"
author = "TheElectronWill"
languages = ["en", "fr"]
date_format = "%Y-%m-%d"
max_listed_posts = 8
max_listed_taxos = 12

[engine]
input = "."
output = ".."
extensions = ["markdown.extensions.codehilite", "markdown.extensions.extra", "mdx_math"]
symlink_static_resources = true

[i18n.en]
home = "Home"
tags = "Tags"
years = "Years"
github = "My Github"
about = "About me"

[i18n.fr]
home = "Accueil"
tags = "Tags"
years = "Années"
github = "Mon Github"
about = "À propos de moi"
